---
title: "Harry Styles Album Leak - Twitter Word Cloud"
author: "Lissie Bates-Haus"
date: "4/20/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(rtweet)
library(twitteR)
library(leaflet)
library(quanteda)
library(readr)
library(httr)

# load libraries
library(tidytext)
library(plyr)
library(tidyverse)
library(quanteda.textmodels)
library(tm)

```

Harry Styles Tweets

```{r}

setwd("~/DACCS R/Text as Data/911Fox Project")


# COLLECT TWEETS
#token is for rtweet
#First run - practice getting tweets that mention taylorswift by username
mytoken <- create_token(
  app = "TaD TSwift Project", #app name here
  consumer_key = "jsmZktV4NSA8mPKv2V3ltwrW3", #consumer key here
  consumer_secret = "rEFDgrLdul03szTPZjJLAhvfzc29ywhmukp3KlSaLIsQhXuGGm", #consumer secret here
  access_token = "1179567891873763330-LfrnHKrJvSsNkGQHMCbFQPyISjAdR7", #access token here
  access_secret = "eW6riAMQQEQtdK7VryAqpYmuLXRFvgBQG6KxPno3WdmKB") #access secret here

HarryStylesLeak <- search_tweets("Harry's House", n = 10000, token=mytoken, include_rts = FALSE, lang = "en") 

write_as_csv(HarryStylesLeak,"HarryStylesLeak.csv")

```

